2024-02-12 15:04:57,459 INFO    StreamThr :60891 [internal.py:wandb_internal():86] W&B internal server running at pid: 60891, started at: 2024-02-12 15:04:57.457967
2024-02-12 15:04:57,461 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: status
2024-02-12 15:04:57,462 INFO    WriterThread:60891 [datastore.py:open_for_write():85] open: /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240212_150447-st3d8c8k/run-st3d8c8k.wandb
2024-02-12 15:04:57,465 DEBUG   SenderThread:60891 [sender.py:send():382] send: header
2024-02-12 15:04:57,465 DEBUG   SenderThread:60891 [sender.py:send():382] send: run
2024-02-12 15:04:58,091 INFO    SenderThread:60891 [dir_watcher.py:__init__():211] watching files in: /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240212_150447-st3d8c8k/files
2024-02-12 15:04:58,091 INFO    SenderThread:60891 [sender.py:_start_run_threads():1136] run started: st3d8c8k with start time 1707710696.616345
2024-02-12 15:04:58,107 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: check_version
2024-02-12 15:04:58,108 DEBUG   SenderThread:60891 [sender.py:send_request():409] send_request: check_version
2024-02-12 15:04:58,262 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: run_start
2024-02-12 15:04:58,264 DEBUG   HandlerThread:60891 [system_info.py:__init__():32] System info init
2024-02-12 15:04:58,264 DEBUG   HandlerThread:60891 [system_info.py:__init__():47] System info init done
2024-02-12 15:04:58,264 INFO    HandlerThread:60891 [system_monitor.py:start():194] Starting system monitor
2024-02-12 15:04:58,264 INFO    SystemMonitor:60891 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-12 15:04:58,265 INFO    HandlerThread:60891 [system_monitor.py:probe():214] Collecting system info
2024-02-12 15:04:58,265 INFO    SystemMonitor:60891 [interfaces.py:start():190] Started cpu monitoring
2024-02-12 15:04:58,267 DEBUG   HandlerThread:60891 [system_info.py:probe():196] Probing system
2024-02-12 15:04:58,267 INFO    SystemMonitor:60891 [interfaces.py:start():190] Started disk monitoring
2024-02-12 15:04:58,268 INFO    SystemMonitor:60891 [interfaces.py:start():190] Started gpuapple monitoring
2024-02-12 15:04:58,270 INFO    SystemMonitor:60891 [interfaces.py:start():190] Started memory monitoring
2024-02-12 15:04:58,273 INFO    SystemMonitor:60891 [interfaces.py:start():190] Started network monitoring
2024-02-12 15:04:58,274 DEBUG   HandlerThread:60891 [system_info.py:_probe_git():181] Probing git
2024-02-12 15:04:58,305 DEBUG   HandlerThread:60891 [system_info.py:_probe_git():189] Probing git done
2024-02-12 15:04:58,305 DEBUG   HandlerThread:60891 [system_info.py:probe():244] Probing system done
2024-02-12 15:04:58,305 DEBUG   HandlerThread:60891 [system_monitor.py:probe():223] {'os': 'macOS-13.5.1-arm64-arm-64bit', 'python': '3.11.5', 'heartbeatAt': '2024-02-12T04:04:58.267712', 'startedAt': '2024-02-12T04:04:47.902108', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'Documents/GitHub/Data_Distill_with_NC/DD&NC_Demo(1st_order).ipynb', 'codePathLocal': None, 'root': '/Users/songzeyang/Documents/GitHub/Data_Distill_with_NC', 'git': {'remote': 'https://github.com/SongzeYang0721/Data_Distillation_and_Neural_Collpase.git', 'commit': '7d011fb14f45690554288b4c3985040d70f57bcb'}, 'email': 'yangsongze2008@gmail.com', 'host': 'Songzes-MacBook-Pro.local', 'username': 'songzeyang', 'executable': '/Users/songzeyang/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 460.4317207336426, 'used': 162.8498764038086}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-02-12 15:04:58,305 INFO    HandlerThread:60891 [system_monitor.py:probe():224] Finished collecting system info
2024-02-12 15:04:58,305 INFO    HandlerThread:60891 [system_monitor.py:probe():227] Publishing system info
2024-02-12 15:04:58,305 DEBUG   HandlerThread:60891 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-02-12 15:04:58,306 DEBUG   HandlerThread:60891 [system_info.py:_save_pip():68] Saving pip packages done
2024-02-12 15:04:58,306 DEBUG   HandlerThread:60891 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-02-12 15:04:59,093 INFO    Thread-26 :60891 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240212_150447-st3d8c8k/files/requirements.txt
2024-02-12 15:04:59,094 INFO    Thread-26 :60891 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240212_150447-st3d8c8k/files/conda-environment.yaml
2024-02-12 15:05:02,529 DEBUG   HandlerThread:60891 [system_info.py:_save_conda():87] Saving conda packages done
2024-02-12 15:05:02,530 INFO    HandlerThread:60891 [system_monitor.py:probe():229] Finished publishing system info
2024-02-12 15:05:02,530 DEBUG   SenderThread:60891 [sender.py:send():382] send: files
2024-02-12 15:05:02,531 INFO    SenderThread:60891 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-02-12 15:05:02,531 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: status_report
2024-02-12 15:05:02,543 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: stop_status
2024-02-12 15:05:02,543 DEBUG   SenderThread:60891 [sender.py:send_request():409] send_request: stop_status
2024-02-12 15:05:02,544 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:05:02,893 DEBUG   SenderThread:60891 [sender.py:send():382] send: telemetry
2024-02-12 15:05:03,104 INFO    Thread-26 :60891 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240212_150447-st3d8c8k/files/conda-environment.yaml
2024-02-12 15:05:03,106 INFO    Thread-26 :60891 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240212_150447-st3d8c8k/files/wandb-metadata.json
2024-02-12 15:05:03,106 INFO    Thread-26 :60891 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240212_150447-st3d8c8k/files/output.log
2024-02-12 15:05:03,519 INFO    wandb-upload_0:60891 [upload_job.py:push():131] Uploaded file /var/folders/50/9xzt17gx7hz47b3vjql39fjh0000gn/T/tmp6k9bt0xywandb/50mknptn-wandb-metadata.json
2024-02-12 15:05:05,113 INFO    Thread-26 :60891 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240212_150447-st3d8c8k/files/output.log
2024-02-12 15:05:07,918 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: status_report
2024-02-12 15:05:12,939 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: status_report
2024-02-12 15:05:17,547 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: stop_status
2024-02-12 15:05:17,548 DEBUG   SenderThread:60891 [sender.py:send_request():409] send_request: stop_status
2024-02-12 15:05:17,551 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:05:18,862 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: status_report
2024-02-12 15:05:23,880 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: status_report
2024-02-12 15:05:28,902 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: status_report
2024-02-12 15:05:29,125 ERROR   SenderThread:60891 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 15:05:29,125 ERROR   SenderThread:60891 [internal_api.py:execute():374] {"errors":[{"message":"run data-distillation-with-nc/DD\u0026NC/st3d8c8k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 15:05:30,416 ERROR   SenderThread:60891 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 15:05:30,417 ERROR   SenderThread:60891 [internal_api.py:execute():374] {"errors":[{"message":"run data-distillation-with-nc/DD\u0026NC/st3d8c8k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 15:05:32,551 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: stop_status
2024-02-12 15:05:32,553 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:05:32,786 ERROR   SenderThread:60891 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 15:05:32,786 ERROR   SenderThread:60891 [internal_api.py:execute():374] {"errors":[{"message":"run data-distillation-with-nc/DD\u0026NC/st3d8c8k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 15:05:32,787 INFO    SenderThread:60891 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-02-12 15:05:37,572 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:05:37,754 ERROR   SenderThread:60891 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 15:05:37,754 ERROR   SenderThread:60891 [internal_api.py:execute():374] {"errors":[{"message":"run data-distillation-with-nc/DD\u0026NC/st3d8c8k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 15:05:42,589 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:05:47,041 ERROR   SenderThread:60891 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 15:05:47,042 ERROR   SenderThread:60891 [internal_api.py:execute():374] {"errors":[{"message":"run data-distillation-with-nc/DD\u0026NC/st3d8c8k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 15:05:47,558 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:05:52,615 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:05:57,630 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:05:58,276 DEBUG   SystemMonitor:60891 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-12 15:06:02,564 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:06:05,158 ERROR   SenderThread:60891 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 15:06:05,159 ERROR   SenderThread:60891 [internal_api.py:execute():374] {"errors":[{"message":"run data-distillation-with-nc/DD\u0026NC/st3d8c8k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 15:06:07,659 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:06:12,686 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:06:17,566 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:06:22,730 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:06:27,751 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:06:32,570 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:06:37,787 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:06:41,306 ERROR   SenderThread:60891 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 15:06:41,307 ERROR   SenderThread:60891 [internal_api.py:execute():374] {"errors":[{"message":"run data-distillation-with-nc/DD\u0026NC/st3d8c8k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 15:06:42,247 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: partial_history
2024-02-12 15:06:43,103 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:06:47,928 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:06:52,943 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:06:57,963 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:07:02,928 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:07:08,000 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:07:13,022 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:07:17,926 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:07:23,060 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:07:28,078 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:07:32,930 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:07:38,108 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:07:43,126 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: keepalive
2024-02-12 15:07:47,931 DEBUG   HandlerThread:60891 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-12 15:07:48,403 ERROR   SenderThread:60891 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-02-12 15:07:48,403 ERROR   SenderThread:60891 [internal_api.py:execute():374] {"errors":[{"message":"run data-distillation-with-nc/DD\u0026NC/st3d8c8k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-02-12 15:07:48,416 INFO    HandlerThread:60891 [handler.py:finish():866] shutting down handler
2024-02-12 15:07:48,416 INFO    HandlerThread:60891 [system_monitor.py:finish():203] Stopping system monitor
2024-02-12 15:07:48,417 DEBUG   SystemMonitor:60891 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-12 15:07:48,417 DEBUG   SystemMonitor:60891 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-12 15:07:48,422 INFO    WriterThread:60891 [datastore.py:close():294] close: /Users/songzeyang/Documents/GitHub/Data_Distill_with_NC/wandb/run-20240212_150447-st3d8c8k/run-st3d8c8k.wandb
2024-02-12 15:07:48,425 INFO    HandlerThread:60891 [interfaces.py:finish():202] Joined cpu monitor
2024-02-12 15:07:48,428 INFO    HandlerThread:60891 [interfaces.py:finish():202] Joined disk monitor
2024-02-12 15:07:48,645 INFO    HandlerThread:60891 [interfaces.py:finish():202] Joined gpuapple monitor
2024-02-12 15:07:48,645 INFO    HandlerThread:60891 [interfaces.py:finish():202] Joined memory monitor
2024-02-12 15:07:48,645 INFO    HandlerThread:60891 [interfaces.py:finish():202] Joined network monitor
2024-02-12 15:07:49,104 ERROR   StreamThr :60891 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2212, in upsert_run
    response = self.gql(
               ^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal.py", line 334, in _debounce
    self._sm.debounce()
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 540, in debounce
    self._maybe_update_config(always=final)
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 517, in _maybe_update_config
    self._debounce_config()
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 546, in _debounce_config
    self._api.upsert_run(
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run data-distillation-with-nc/DD&NC/st3d8c8k was previously created and deleted; try a new run name (Error 409: Conflict)
