Dataset: CIFAR10.
Files already downloaded and verified
Files already downloaded and verified
10
The number of class in our training set is  10
Batch size: 2048 Number of channels: 3 input height: 32 input width: 32
override this uidtmp
<arg_loader.train_args object at 0x1649fe290>
cudnn is used
# of model parameters: 11176522
<class 'models.resnet.ResNet'>
override this uidtmp
<arg_loader.train_args object at 0x29c589510>
cudnn is used
Dataset: CIFAR10.
Files already downloaded and verified
Files already downloaded and verified
10
The number of class in our training set is  10
Batch size: 2048 Number of channels: 3 input height: 32 input width: 32
# of model parameters: 11176522
<class 'models.resnet.ResNet'>
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x14f00d6c0>
Traceback (most recent call last):
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1458, in _shutdown_workers
    _utils.signal_handling._remove_worker_pids(id(self))
                                               ^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 5782) is killed by signal: Interrupt: 2.
override this uidtmp
<arg_loader.train_args object at 0x16880ec50>
cudnn is used
Dataset: CIFAR10.
Files already downloaded and verified
Files already downloaded and verified
10
The number of class in our training set is  10
Batch size: 2048 Number of channels: 3 input height: 32 input width: 32
# of model parameters: 11176522
<class 'models.resnet.ResNet'>
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x14f00d6c0>
Traceback (most recent call last):
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1442, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/Users/songzeyang/anaconda3/lib/python3.11/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/multiprocessing/connection.py", line 930, in wait
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
--- Logging error ---
Traceback (most recent call last):
  File "/Users/songzeyang/anaconda3/lib/python3.11/logging/__init__.py", line 1114, in emit
    self.flush()
  File "/Users/songzeyang/anaconda3/lib/python3.11/logging/__init__.py", line 1094, in flush
    self.stream.flush()
OSError: [Errno 5] Input/output error
Call stack:
  File "/Users/songzeyang/anaconda3/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/Users/songzeyang/anaconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/ipykernel/parentpoller.py", line 38, in run
    get_logger().warning("Parent appears to have exited, shutting down.")
Message: 'Parent appears to have exited, shutting down.'
