
[epoch: 1] (1563/1563) | Loss: 2.5784 | top1: 40.8460 | top5: 89.2260
[epoch: 2] (1563/1563) | Loss: 1.4734 | top1: 55.9520 | top5: 94.3820
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x10d114c20>
Traceback (most recent call last):
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/Users/songzeyang/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1442, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/Users/songzeyang/anaconda3/lib/python3.11/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/multiprocessing/connection.py", line 930, in wait
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/songzeyang/anaconda3/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.
<arg_loader.train_args object at 0x143b3f950>
cudnn is used
Dataset: CIFAR10.
Files already downloaded and verified
Files already downloaded and verified
10
The number of class in our training set is  10
Batch size: 32 Number of channels: 3 input height: 32 input width: 32
# of model parameters: 8859762
<class 'models.resnet.ResNet'>